<?php 
/**
* This file is the main template that "contains" what has been generated by the other views.
* The variables that must be defined are:
* `$title` (string): the page title.
* `$content` (string): the page content.
*/

?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?></title>
    <link rel="stylesheet" href="src/styles/main.css">
    <link rel="stylesheet" href="src/styles/home.css">
    <!-- Police Inter -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
</head>

<body>
    <header>
        <nav>
            <ul>
                <li><img src="public/img/logo.svg" alt="logo du site TomTroc"/></li>
                <li><a href="index.php">Accueil</a></li>
                <li><a href="index.php?type=Book&action=post">Nos livres à l’échange</a></li>
            </ul>
            <!-- add the dynamique bar -->
            <ul>
                <li><a href="index.php">Messagerie</a></li>
                <li><a href="index.php">Mon compte</a></li>
                <li><a href="index.php">Connexion</a></li>
            </ul>
        </nav>
    </header>

    <main>    
        <?= $content ?>
    </main>
    
    <footer>
        <p>Bas de page</p>
    </footer>

</body>
</html>